require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TopsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Top. As you add validations to Top, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TopsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all tops as @tops" do
      top = Top.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:tops)).to eq([top])
    end
  end

  describe "GET #show" do
    it "assigns the requested top as @top" do
      top = Top.create! valid_attributes
      get :show, params: {id: top.to_param}, session: valid_session
      expect(assigns(:top)).to eq(top)
    end
  end

  describe "GET #new" do
    it "assigns a new top as @top" do
      get :new, params: {}, session: valid_session
      expect(assigns(:top)).to be_a_new(Top)
    end
  end

  describe "GET #edit" do
    it "assigns the requested top as @top" do
      top = Top.create! valid_attributes
      get :edit, params: {id: top.to_param}, session: valid_session
      expect(assigns(:top)).to eq(top)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Top" do
        expect {
          post :create, params: {top: valid_attributes}, session: valid_session
        }.to change(Top, :count).by(1)
      end

      it "assigns a newly created top as @top" do
        post :create, params: {top: valid_attributes}, session: valid_session
        expect(assigns(:top)).to be_a(Top)
        expect(assigns(:top)).to be_persisted
      end

      it "redirects to the created top" do
        post :create, params: {top: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Top.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved top as @top" do
        post :create, params: {top: invalid_attributes}, session: valid_session
        expect(assigns(:top)).to be_a_new(Top)
      end

      it "re-renders the 'new' template" do
        post :create, params: {top: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested top" do
        top = Top.create! valid_attributes
        put :update, params: {id: top.to_param, top: new_attributes}, session: valid_session
        top.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested top as @top" do
        top = Top.create! valid_attributes
        put :update, params: {id: top.to_param, top: valid_attributes}, session: valid_session
        expect(assigns(:top)).to eq(top)
      end

      it "redirects to the top" do
        top = Top.create! valid_attributes
        put :update, params: {id: top.to_param, top: valid_attributes}, session: valid_session
        expect(response).to redirect_to(top)
      end
    end

    context "with invalid params" do
      it "assigns the top as @top" do
        top = Top.create! valid_attributes
        put :update, params: {id: top.to_param, top: invalid_attributes}, session: valid_session
        expect(assigns(:top)).to eq(top)
      end

      it "re-renders the 'edit' template" do
        top = Top.create! valid_attributes
        put :update, params: {id: top.to_param, top: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested top" do
      top = Top.create! valid_attributes
      expect {
        delete :destroy, params: {id: top.to_param}, session: valid_session
      }.to change(Top, :count).by(-1)
    end

    it "redirects to the tops list" do
      top = Top.create! valid_attributes
      delete :destroy, params: {id: top.to_param}, session: valid_session
      expect(response).to redirect_to(tops_url)
    end
  end

end
